export const phases = [
  {
    name: "Capture",
    text: "Put the right homeowner offer in front of the right market through the appropriate acquisition channel and conversion assets.",
  },
  {
    name: "Convert",
    text: "Connect new inquiries to rapid response, qualification, booking, reminders, and a clear next step.",
  },
  {
    name: "Recover",
    text: "Follow up on unresponsive leads, missed appointments, delayed projects, and open estimates.",
  },
  {
    name: "Compound",
    text: "Turn completed jobs and past customers into reviews, referrals, repeat service, reactivation, and appropriate additional offers.",
  },
];
export const timeline = [
  {
    days: "Days 1-30",
    name: "Build",
    text: "Map the economics and customer journey. Select the priority service and strengthen the homeowner offer. Build the primary funnel, configure the CRM and tracking, install response and booking workflows, and prepare the acquisition campaign.",
  },
  {
    days: "Days 31-60",
    name: "Convert",
    text: "Operate the campaign. Review lead quality, improve response, booking and show rates, and test creative and messaging.",
  },
  {
    days: "Days 61-90",
    name: "Recover",
    text: "Launch the primary recovery system. Follow up on open estimates, no-shows or dormant opportunities, and measure recovered opportunities.",
  },
  {
    days: "Days 91-120",
    name: "Compound",
    text: "Install the referral foundation. Launch one repeat-service, reactivation, referral or cross-sell campaign. Produce the Revenue Proof Review and next-quarter plan.",
  },
];
export const implementation = [
  "Revenue Blueprint",
  "Economic Fit Test",
  "Revenue Leakage Map",
  "Baseline KPI scorecard",
  "One priority homeowner offer",
  "One primary business location",
  "One paid acquisition platform",
  "One primary funnel",
  "Up to two page assets",
  "One GHL pipeline and agreed integration",
  "Initial tracking configuration",
  "Initial campaign setup",
  "Six initial creative assets across up to three angles",
  "Rapid lead-response workflows",
  "Qualification and booking architecture",
  "One primary opportunity-recovery workflow",
  "Referral foundation",
  "One Customer Expansion Campaign",
  "Aurex Revenue Command Center",
  "Front-office scripts",
  "One recorded staff training",
  "Launch quality assurance",
];
export const operations = [
  "Management of one agreed acquisition platform",
  "Weekly campaign optimization",
  "Lead-quality review",
  "Selected call or lead-disposition review",
  "GHL workflow monitoring",
  "Four new creative variations per month",
  "One meaningful funnel or follow-up test per month",
  "Weekly performance scorecard",
  "Monthly Revenue Proof Review",
  "Monthly strategy call",
  "Reasonable maintenance of the systems Aurex built",
];
export const excluded = [
  "Full website redesign",
  "SEO retainer",
  "Daily organic social posting",
  "Unlimited landing pages",
  "Unlimited creative",
  "Multiple locations",
  "Multiple acquisition platforms",
  "Major CRM migration",
  "On-site video production",
  "Unlimited revisions",
  "Full-time call answering",
  "Human appointment-setting desk",
  "Closing homeowner sales",
  "Managing the client’s entire sales team",
  "Reputation repair",
  "Legal compliance services",
  "Advertising spend",
  "Third-party software, messaging, calling, and usage costs",
];
export const responsibilities = [
  "Provide required access within three business days",
  "Assign one decision-maker",
  "Approve or revise assets within two business days",
  "Maintain the agreed advertising budget",
  "Maintain enough capacity to fulfill additional work",
  "Have staff available for live lead conversations",
  "Follow the agreed lead-handling process",
  "Keep opportunity stages current",
  "Report appointments, estimates, sales, and collected revenue",
  "Participate in kickoff, training, and monthly reviews",
  "Supply permission-compliant customer data for recovery and customer-growth campaigns",
];
export const launchChecks = [
  "Primary page published",
  "Forms submit correctly",
  "Lead source recorded",
  "Lead enters GHL correctly",
  "Internal notification delivered",
  "Lead acknowledgement delivered",
  "Booking flow tested",
  "Appointment reminders tested",
  "Recovery workflow triggers correctly",
  "Campaign tracking verified",
  "Dashboard receives test data",
];
export const goodFit = [
  "Established residential contractor",
  "Profitable priority service or project",
  "Office, dispatch, sales, or estimating staff",
  "Existing leads or an active acquisition budget",
  "Capacity to take on more work",
  "Willingness to track appointments, estimates, sales, and revenue",
  "Owner or general manager involved in the process",
];
export const poorFit = [
  "Solo operator with no lead-handling capacity",
  "Business seeking the cheapest possible leads",
  "Company unable to fulfill more work",
  "Owner unwilling to provide sales data",
  "Business expecting Aurex to answer every call and close every homeowner inside the base engagement",
];
